# Generated by Django 6.0.4 on 2026-05-03 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=255)),
                ('game_cover', models.URLField(max_length=500)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('review', 'Reseña'), ('status', 'Estado'), ('screenshot', 'Captura')], default='status', max_length=20)),
                ('rating', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='playlog',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='playlog',
            name='core_playlo_user_id_623a07_idx',
        ),
        migrations.AddField(
            model_name='activitypost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PlayLog',
        ),
    ]
