# Generated by Django 6.0.4 on 2026-05-04 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('game_name', models.CharField(max_length=255)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('playing', 'Jugando'), ('finished', 'Terminado'), ('completed', 'Completado'), ('backlog', 'Backlog'), ('abandoned', 'Abandonado')], default='backlog', max_length=20)),
                ('rating', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
