# Generated by Django 6.0.4 on 2026-05-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usergame'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergame',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usergame',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usergame',
            name='platform',
            field=models.CharField(blank=True, default='No especificada', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='status',
            field=models.CharField(choices=[('playing', 'Jugando'), ('finished', 'Terminado'), ('completed', 'Completado'), ('backlog', 'Backlog'), ('paused', 'Pausado'), ('abandoned', 'Abandonado'), ('needs_attention', 'Necesita Atención')], default='backlog', max_length=20),
        ),
    ]
