# Generated by Django 6.0.4 on 2026-05-04 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usergame_hours_usergame_minutes_usergame_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
                ('game_id', models.IntegerField()),
                ('game_name', models.CharField(max_length=255)),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'slot')},
            },
        ),
    ]
