# Generated by Django 6.0.4 on 2026-05-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='game_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
