# Generated by Django 6.0.4 on 2026-05-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergame',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
    ]
